language: python
python:
  - "3.6" # current default Python on Travis CI
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script:
  - "pytest --cov=cathpy"
before_install:
  - "pip install pytest-cov codecov"
after_success:
  - "codecov"
