version: "3.3"

volumes:
  db-store:
  www-static:
  www-logs:

services:
  redis:
    restart: always
    build:
      context: ./redis/
    networks:
      default:
        aliases:
          - redis

  luigi:
    image: axiom/docker-luigi:latest-alpine
    networks:
      default:
        aliases:
          - luigi

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db-store:/var/lib/postgresql/data/

  app:
    build:
      context: ../
      dockerfile: Docker/app/Dockerfile
    depends_on:
      - redis
      - luigi
    environment:
      - FLASK_DEBUG=0
      - ALLOWED_HOSTS=$ALLOWED_HOSTS
      - DATABASE_NAME=$POSTGRES_DB
      - DATABASE_WRITER_USER=$POSTGRES_USER
      - DATABASE_WRITER_PASSWORD=$POSTGRES_DB
    ports:
      - "5000:5000"
    volumes:
      - www-static:/static

  nginx:
    restart: always
    build:
      context: ./nginx/
    depends_on:
      - app
    volumes:
      - www-static:/static
      - www-logs:/var/log/nginx
    ports:
      - "0.0.0.0:80:8000"
