"""empty message

Revision ID: 77615a2829d4
Revises: 
Create Date: 2021-03-03 14:37:34.364350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77615a2829d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_structure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('original_path', sa.String(), nullable=False),
    sa.Column('identity', sa.Numeric(), nullable=True),
    sa.Column('similarity', sa.Numeric(), nullable=True),
    sa.Column('oligo_state', sa.String(), nullable=True),
    sa.Column('coverage', sa.Numeric(), nullable=True),
    sa.Column('qmean_version', sa.String(), nullable=True),
    sa.Column('qmean_avg_local_score', sa.Numeric(), nullable=True),
    sa.Column('pdb_created_at', sa.DateTime(), nullable=True),
    sa.Column('mmcif_created_at', sa.DateTime(), nullable=True),
    sa.Column('qmean_created_at', sa.DateTime(), nullable=True),
    sa.Column('model_data_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_chain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.String(), nullable=False),
    sa.Column('model_structure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_structure_id'], ['model_structure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_chain_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seqres_from', sa.Integer(), nullable=True),
    sa.Column('seqres_to', sa.Integer(), nullable=True),
    sa.Column('seqres_aligned_sequence', sa.String(), nullable=True),
    sa.Column('uniprot_acc', sa.String(), nullable=False),
    sa.Column('uniprot_id', sa.String(), nullable=False),
    sa.Column('uniprot_length', sa.Integer(), nullable=False),
    sa.Column('uniprot_md5', sa.String(), nullable=True),
    sa.Column('uniprot_aligned_sequence', sa.String(), nullable=False),
    sa.Column('uniprot_from', sa.Integer(), nullable=False),
    sa.Column('uniprot_to', sa.Integer(), nullable=False),
    sa.Column('model_chain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_chain_id'], ['model_chain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_chain_segment_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('chain_id', sa.String(), nullable=False),
    sa.Column('template_sequence_identity', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('experimental_method', sa.String(), nullable=False),
    sa.Column('resolution', sa.Float(), nullable=False),
    sa.Column('preferred_assembly_id', sa.String(), nullable=True),
    sa.Column('model_chain_segment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_chain_segment_id'], ['model_chain_segment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_chain_segment_template')
    op.drop_table('model_chain_segment')
    op.drop_table('model_chain')
    op.drop_table('model_structure')
    # ### end Alembic commands ###
