name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: test
          MONGO_INITDB_DATABASE: models
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Gemmi
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda install -c conda-forge gemmi

      - name: Run tests
        run: make test
        env:
          MONGO_USERNAME: test
          MONGO_PASSWORD: test
          PROVIDER: test
          MONGO_DB_HOST: localhost:27017
          MODEL_FORMAT: MMCIF
          ASSETS_URL: localhost/static
